# Generated by Django 5.2.13 on 2026-04-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_project_description_alter_project_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'Запланированно'), ('In Progress', 'В процессе'), ('Done', 'Сделано')], default='To Do'),
        ),
    ]
