# Generated by Django 5.2.13 on 2026-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='tasks.tag'),
        ),
    ]
